export { injectQuotaGuard } from './setup.js';
export { getConfig, setConfig, defineConfig, type QuotaGuardConfig, type AuditEvent } from './config.js';
export { globalCache, MemoryCache } from './cache/memory.js';
export { BrowserCache } from './cache/browser.js';
export { FileCache } from './cache/file.js';
export { BaseCache } from './cache/base.js';
export { type SerializedCacheEntry, type ICacheAdapter, type RequestMetadata } from './cache/types.js';
export { globalBreaker, CircuitBreaker, CircuitBreakerError } from './breaker/circuit-breaker.js';
export { globalInFlightRegistry, InFlightRegistry } from './registry/in-flight.js';
export { removeGlobalGuards } from './core/interceptor.js';
