#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

while read local_ref local_sha remote_ref remote_sha
do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    echo "❌ Error: Direct pushes to 'main' are forbidden."
    echo "All changes must be merged via PR on GitHub."
    exit 1
  fi
done
