#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "❌ Error: Direct commits/merges to 'main' are forbidden."
  echo "Please use a feature/fix branch and submit a PR on GitHub."
  exit 1
fi
